version: "3.9"
services:
    autohaus:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile.prod
            network: "${DOCKER_NETWORK}" 
        ports:
            - 3006:3000
        volumes:
            - .swc:/app/swc
            - ./components:/app/components
            - ./lib:/app/lib
            - ./pages:/app/pages
            - ./strapiAPI:/app/strapiAPI
            - ./styles:/app/styles
            - ./.env:/app/.env 
        command: "npm run server"
        restart: always
        deploy:
            resources:
                limits:
                    cpus: '1.25'
                    memory: 2000m
networks:
    default:
        external: true
        name: "${DOCKER_NETWORK}"